//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipAngel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class internalVisibleUserSettings
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal internalVisibleUserSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipAngel.VisibleUserSettings", typeof(internalVisibleUserSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow download thumbnail.
        /// </summary>
        internal static string AllowDownloadThumbnail {
            get {
                return ResourceManager.GetString("AllowDownloadThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow download thumbnail for video and image links from internet.
        /// </summary>
        internal static string AllowDownloadThumbnailDescription {
            get {
                return ResourceManager.GetString("AllowDownloadThumbnailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocheck for program update.
        /// </summary>
        internal static string AutoCheckUpdate {
            get {
                return ResourceManager.GetString("AutoCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocheck for update on program start and every day.
        /// </summary>
        internal static string AutoCheckUpdateDescription {
            get {
                return ResourceManager.GetString("AutoCheckUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoselect first match.
        /// </summary>
        internal static string AutoSelectMatch {
            get {
                return ResourceManager.GetString("AutoSelectMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoselection of first match of search string in clip text. .
        /// </summary>
        internal static string AutoSelectMatchDescription {
            get {
                return ResourceManager.GetString("AutoSelectMatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoselect matched clip.
        /// </summary>
        internal static string AutoSelectMatchedClip {
            get {
                return ResourceManager.GetString("AutoSelectMatchedClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When filter by search string is off and search string is changed, automatically go to first clip matched search string.
        /// </summary>
        internal static string AutoSelectMatchedClipDescription {
            get {
                return ResourceManager.GetString("AutoSelectMatchedClipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart program on user logon.
        /// </summary>
        internal static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AutostartDescription {
            get {
                return ResourceManager.GetString("AutostartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application autostart command line.
        /// </summary>
        internal static string AutostartPath {
            get {
                return ResourceManager.GetString("AutostartPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to update this command from current start path.
        /// </summary>
        internal static string AutostartPathDescription {
            get {
                return ResourceManager.GetString("AutostartPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture images.
        /// </summary>
        internal static string CaptureImages {
            get {
                return ResourceManager.GetString("CaptureImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture image clips.
        /// </summary>
        internal static string CaptureImagesDescription {
            get {
                return ResourceManager.GetString("CaptureImagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters on main window close.
        /// </summary>
        internal static string ClearFiltersOnClose {
            get {
                return ResourceManager.GetString("ClearFiltersOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ClearFiltersOnCloseDescription {
            get {
                return ResourceManager.GetString("ClearFiltersOnCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast and simple list draw.
        /// </summary>
        internal static string ClipListSimpleDraw {
            get {
                return ResourceManager.GetString("ClipListSimpleDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip list will be drawn fast without highlighting filter matches and picture samples.
        /// </summary>
        internal static string ClipListSimpleDrawDescription {
            get {
                return ResourceManager.GetString("ClipListSimpleDrawDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder for clip temp files.
        /// </summary>
        internal static string ClipTempFileFolder {
            get {
                return ResourceManager.GetString("ClipTempFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder for saving temp files of clips. Leave empty to use standard temp folder. Usually can be usefull in portable mode..
        /// </summary>
        internal static string ClipTempFileFolderDescription {
            get {
                return ResourceManager.GetString("ClipTempFileFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation before delete.
        /// </summary>
        internal static string ConfirmationBeforeDelete {
            get {
                return ResourceManager.GetString("ConfirmationBeforeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask confirmation before clip delete.
        /// </summary>
        internal static string ConfirmationBeforeDeleteDescription {
            get {
                return ResourceManager.GetString("ConfirmationBeforeDeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy text from any window by Control+F3.
        /// </summary>
        internal static string CopyTextInAnyWindowOnCTRLF3 {
            get {
                return ResourceManager.GetString("CopyTextInAnyWindowOnCTRLF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected text from any window when Control+F3 is pressed. This hotkey usually is used in text editors to search selected string. 
        ///Key press will be processed by the window. .
        /// </summary>
        internal static string CopyTextInAnyWindowOnCTRLF3Description {
            get {
                return ResourceManager.GetString("CopyTextInAnyWindowOnCTRLF3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application current start path.
        /// </summary>
        internal static string CurrentPath {
            get {
                return ResourceManager.GetString("CurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file.
        /// </summary>
        internal static string DatabaseFile {
            get {
                return ResourceManager.GetString("DatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change database filename to switch to other clipboard history. 
        ///Leave blank to use standard database file &quot;db.sqlite&quot; in application user settings folder..
        /// </summary>
        internal static string DatabaseFileDescription {
            get {
                return ResourceManager.GetString("DatabaseFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database size MB.
        /// </summary>
        internal static string DatabaseSize {
            get {
                return ResourceManager.GetString("DatabaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseSizeDescription {
            get {
                return ResourceManager.GetString("DatabaseSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default font.
        /// </summary>
        internal static string DefaultFont {
            get {
                return ResourceManager.GetString("DefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font for clip list and default for clip text. Double click to change it..
        /// </summary>
        internal static string DefaultFontDescription {
            get {
                return ResourceManager.GetString("DefaultFontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete non favorite clips on exit.
        /// </summary>
        internal static string DeleteNonFavoriteClipsOnExit {
            get {
                return ResourceManager.GetString("DeleteNonFavoriteClipsOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all non favorite clips after close database.
        /// </summary>
        internal static string DeleteNonFavoriteClipsOnExitDescription {
            get {
                return ResourceManager.GetString("DeleteNonFavoriteClipsOnExitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter for text join.
        /// </summary>
        internal static string DelimiterForTextJoin {
            get {
                return ResourceManager.GetString("DelimiterForTextJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter used for text join command. Use &quot;\n&quot; as end of line..
        /// </summary>
        internal static string DelimiterForTextJoinDescription {
            get {
                return ResourceManager.GetString("DelimiterForTextJoinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t send paste to target window.
        /// </summary>
        internal static string DontSendPaste {
            get {
                return ResourceManager.GetString("DontSendPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t send paste to target window in Paste commands. Just put data on clipboard..
        /// </summary>
        internal static string DontSendPasteDescription {
            get {
                return ResourceManager.GetString("DontSendPasteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt database for current user.
        /// </summary>
        internal static string EncryptDatabaseForCurrentUser {
            get {
                return ResourceManager.GetString("EncryptDatabaseForCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set NTFS encryption flag in database file. Only current Windows user will be able to read it..
        /// </summary>
        internal static string EncryptDatabaseForCurrentUserDescription {
            get {
                return ResourceManager.GetString("EncryptDatabaseForCurrentUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast window open.
        /// </summary>
        internal static string FastWindowOpen {
            get {
                return ResourceManager.GetString("FastWindowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast window opening by using some tricks. Can lead to some minor problems in window opening/closing..
        /// </summary>
        internal static string FastWindowOpenDescription {
            get {
                return ResourceManager.GetString("FastWindowOpenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter list by search string.
        /// </summary>
        internal static string FilterListBySearchString {
            get {
                return ResourceManager.GetString("FilterListBySearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter clip list by search string.
        /// </summary>
        internal static string FilterListBySearchStringDescription {
            get {
                return ResourceManager.GetString("FilterListBySearchStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to compare last clips.
        /// </summary>
        internal static string GlobalHotkeyCompareLastClips {
            get {
                return ResourceManager.GetString("GlobalHotkeyCompareLastClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to launch application for comparing last 2 clips.
        /// </summary>
        internal static string GlobalHotkeyCompareLastClipsDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeyCompareLastClipsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to paste and select previous.
        /// </summary>
        internal static string GlobalHotkeyDecrementalPaste {
            get {
                return ResourceManager.GetString("GlobalHotkeyDecrementalPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to paste current clip from ClipAngel list and select previous/lower clip which will be shown in tray tooltip.
        /// </summary>
        internal static string GlobalHotkeyDecrementalPasteDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeyDecrementalPasteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to forced capture clip.
        /// </summary>
        internal static string GlobalHotkeyForcedCapture {
            get {
                return ResourceManager.GetString("GlobalHotkeyForcedCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to copy data with capture in ClipAngel when clipboard monitoring (autocapture changes) is off..
        /// </summary>
        internal static string GlobalHotkeyForcedCaptureDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeyForcedCaptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to paste and select next.
        /// </summary>
        internal static string GlobalHotkeyIncrementalPaste {
            get {
                return ResourceManager.GetString("GlobalHotkeyIncrementalPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to paste current clip from ClipAngel list and select next/upper clip which will be shown in tray tooltip.
        /// </summary>
        internal static string GlobalHotkeyIncrementalPasteDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeyIncrementalPasteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to open window with no changes.
        /// </summary>
        internal static string GlobalHotkeyOpenCurrent {
            get {
                return ResourceManager.GetString("GlobalHotkeyOpenCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to open ClipAngel window with no changes in filter and clip selection. Press again to close the window..
        /// </summary>
        internal static string GlobalHotkeyOpenCurrentDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeyOpenCurrentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to open window with favorites.
        /// </summary>
        internal static string GlobalHotkeyOpenFavorites {
            get {
                return ResourceManager.GetString("GlobalHotkeyOpenFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to show ClipAngel window with favorites only filter. Press again to close the window..
        /// </summary>
        internal static string GlobalHotkeyOpenFavoritesDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeyOpenFavoritesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to open window with reset.
        /// </summary>
        internal static string GlobalHotkeyOpenLast {
            get {
                return ResourceManager.GetString("GlobalHotkeyOpenLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to open ClipAngel window, clear filters and select last clip. Press again to close the window..
        /// </summary>
        internal static string GlobalHotkeyOpenLastDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeyOpenLastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to paste plain text.
        /// </summary>
        internal static string GlobalHotkeyPasteText {
            get {
                return ResourceManager.GetString("GlobalHotkeyPasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to paste last clip as plain text.
        /// </summary>
        internal static string GlobalHotkeyPasteTextDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeyPasteTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to simulate fast keyboard input.
        /// </summary>
        internal static string GlobalHotkeySimulateInput {
            get {
                return ResourceManager.GetString("GlobalHotkeySimulateInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to simulate fast keyboard input of last clip.
        /// </summary>
        internal static string GlobalHotkeySimulateInputDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeySimulateInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to switch clipboard monitoring.
        /// </summary>
        internal static string GlobalHotkeySwitchMonitoring {
            get {
                return ResourceManager.GetString("GlobalHotkeySwitchMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this hot key in any program to switch clipboard monitoring (autocapture changes) by ClipAngel.
        /// </summary>
        internal static string GlobalHotkeySwitchMonitoringDescription {
            get {
                return ResourceManager.GetString("GlobalHotkeySwitchMonitoringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History depth days.
        /// </summary>
        internal static string HistoryDepthDays {
            get {
                return ResourceManager.GetString("HistoryDepthDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of days non favorite clips are stored. Deletion is executed on start, every day, on settings apply. 0 - do not delete..
        /// </summary>
        internal static string HistoryDepthDaysDescription {
            get {
                return ResourceManager.GetString("HistoryDepthDaysDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History depth number.
        /// </summary>
        internal static string HistoryDepthNumber {
            get {
                return ResourceManager.GetString("HistoryDepthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of stored non favorite clips. Deletion is executed on start, every day, on settings apply. 0 - do not delete. Recommended &lt;50K.
        /// </summary>
        internal static string HistoryDepthNumberDescription {
            get {
                return ResourceManager.GetString("HistoryDepthNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML file editor application.
        /// </summary>
        internal static string HtmlEditor {
            get {
                return ResourceManager.GetString("HtmlEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in &quot;Open file&quot; command for clip. Leave empty to use default OS application for edit HTML files..
        /// </summary>
        internal static string HtmlEditorDescription {
            get {
                return ResourceManager.GetString("HtmlEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored applications in clip capture.
        /// </summary>
        internal static string IgnoreApplicationsClipCapture {
            get {
                return ResourceManager.GetString("IgnoreApplicationsClipCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not capture clips from this applications.
        /// </summary>
        internal static string IgnoreApplicationsClipCaptureDescription {
            get {
                return ResourceManager.GetString("IgnoreApplicationsClipCaptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not capture &quot;Clipboard Viewer Ignore&quot; format.
        /// </summary>
        internal static string IgnoreExclusiveFormatClipCapture {
            get {
                return ResourceManager.GetString("IgnoreExclusiveFormatClipCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not capture clip with &quot;Clipboard Viewer Ignore&quot; format present. 
        ///This format is usually  used by password managers when copying passwords to clipboard. Sometimes it may be usefull to switch it OFF temporary..
        /// </summary>
        internal static string IgnoreExclusiveFormatClipCaptureDescription {
            get {
                return ResourceManager.GetString("IgnoreExclusiveFormatClipCaptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore source URLs in clip capture.
        /// </summary>
        internal static string IgnoreUrlsClipCapture {
            get {
                return ResourceManager.GetString("IgnoreUrlsClipCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of substrings that match in clip source URL will ignore clip capture. Delimiters: &quot;,&quot; or &quot;;&quot;.
        /// </summary>
        internal static string IgnoreUrlsClipCaptureDescription {
            get {
                return ResourceManager.GetString("IgnoreUrlsClipCaptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image (PNG) file editor application.
        /// </summary>
        internal static string ImageEditor {
            get {
                return ResourceManager.GetString("ImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in &quot;Open file&quot; command for clip. Leave empty to use default OS application for edit image (PNG) files..
        /// </summary>
        internal static string ImageEditorDescription {
            get {
                return ResourceManager.GetString("ImageEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface language.
        /// </summary>
        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 1C code size to colorize.
        /// </summary>
        internal static string Max1CCodeSizeToColorize {
            get {
                return ResourceManager.GetString("Max1CCodeSizeToColorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 1C (Russian programming platform) code size in chars to colorize syntax. 1C code capture is detected by text content. 0 - do not colorize.
        /// </summary>
        internal static string Max1CCodeSizeToColorizeDescription {
            get {
                return ResourceManager.GetString("Max1CCodeSizeToColorizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max cells to capture formatted text.
        /// </summary>
        internal static string MaxCellsToCaptureFormattedText {
            get {
                return ResourceManager.GetString("MaxCellsToCaptureFormattedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When capturing clip from cells (Excel), capture generated formatted text if number of cells is lower than this. 0 - do not capture. 
        ///Generation of formatted text consumes CPU. If you experience high CPU load, set lower value..
        /// </summary>
        internal static string MaxCellsToCaptureFormattedTextDescription {
            get {
                return ResourceManager.GetString("MaxCellsToCaptureFormattedTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max cells to capture image.
        /// </summary>
        internal static string MaxCellsToCaptureImage {
            get {
                return ResourceManager.GetString("MaxCellsToCaptureImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When capturing clip from cells (Excel), capture generated image if number of cells is lower than this. 0 - do not capture. 
        ///Generation of image consumes CPU. If you experience high CPU load, set lower value..
        /// </summary>
        internal static string MaxCellsToCaptureImageDescription {
            get {
                return ResourceManager.GetString("MaxCellsToCaptureImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max clip size KB.
        /// </summary>
        internal static string MaxClipSizeKB {
            get {
                return ResourceManager.GetString("MaxClipSizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clips greater this size will not be captured.
        /// </summary>
        internal static string MaxClipSizeKBDescription {
            get {
                return ResourceManager.GetString("MaxClipSizeKBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monospaced font.
        /// </summary>
        internal static string MonospacedFont {
            get {
                return ResourceManager.GetString("MonospacedFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monospaced font in clip text field. 
        ///Could be overloaded by RTF native formatting.
        ///Not appliable to HTML native formatting..
        /// </summary>
        internal static string MonospacedFontDescription {
            get {
                return ResourceManager.GetString("MonospacedFontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move clips to top after use.
        /// </summary>
        internal static string MoveCopiedClipToTop {
            get {
                return ResourceManager.GetString("MoveCopiedClipToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move copied from list or fully pasted clips to top of list.
        /// </summary>
        internal static string MoveCopiedClipToTopDescription {
            get {
                return ResourceManager.GetString("MoveCopiedClipToTopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of clips.
        /// </summary>
        internal static string NumberOfClips {
            get {
                return ResourceManager.GetString("NumberOfClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current number of clips in database.
        /// </summary>
        internal static string NumberOfClipsDescription {
            get {
                return ResourceManager.GetString("NumberOfClipsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound on clip capture.
        /// </summary>
        internal static string PlaySoundOnClipCapture {
            get {
                return ResourceManager.GetString("PlaySoundOnClipCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing sound when clip is successfully captured. Can be annoying.
        /// </summary>
        internal static string PlaySoundOnClipCaptureDescription {
            get {
                return ResourceManager.GetString("PlaySoundOnClipCaptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read window titles.
        /// </summary>
        internal static string ReadWindowTitles {
            get {
                return ResourceManager.GetString("ReadWindowTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read window titles from clip sources. Uncheck this setting to avoid crashes of program on some systems..
        /// </summary>
        internal static string ReadWindowTitlesDescription {
            get {
                return ResourceManager.GetString("ReadWindowTitlesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace duplicates.
        /// </summary>
        internal static string ReplaceDuplicates {
            get {
                return ResourceManager.GetString("ReplaceDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep clips unique by content. Update existing duplicate clip instead of creating new..
        /// </summary>
        internal static string ReplaceDuplicatesDescription {
            get {
                return ResourceManager.GetString("ReplaceDuplicatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore caret position on focus return.
        /// </summary>
        internal static string RestoreCaretPositionOnFocusReturn {
            get {
                return ResourceManager.GetString("RestoreCaretPositionOnFocusReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this to try restore caret position after focus is returned to target window. This is usefull for textboxes which select all text after loosing focus.
        /// </summary>
        internal static string RestoreCaretPositionOnFocusReturnDescription {
            get {
                return ResourceManager.GetString("RestoreCaretPositionOnFocusReturnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTF file editor application.
        /// </summary>
        internal static string RtfEditor {
            get {
                return ResourceManager.GetString("RtfEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in &quot;Open file&quot; command for clip. Leave empty to use default OS application for edit RTF files..
        /// </summary>
        internal static string RtfEditorDescription {
            get {
                return ResourceManager.GetString("RtfEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all fields.
        /// </summary>
        internal static string SearchAllFields {
            get {
                return ResourceManager.GetString("SearchAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False - search only in Text and Title of clips. True - search in Text, Title, Window, Url of clips..
        /// </summary>
        internal static string SearchAllFieldsDescription {
            get {
                return ResourceManager.GetString("SearchAllFieldsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search case sensitive.
        /// </summary>
        internal static string SearchCaseSensitive {
            get {
                return ResourceManager.GetString("SearchCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search filter case sensitive. For example &quot;Pot&quot; will match &quot;Potato&quot;, but not &quot;potato&quot;. .
        /// </summary>
        internal static string SearchCaseSensitiveDescription {
            get {
                return ResourceManager.GetString("SearchCaseSensitiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with ignore big texts.
        /// </summary>
        internal static string SearchIgnoreBigTexts {
            get {
                return ResourceManager.GetString("SearchIgnoreBigTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with ignore big (visual size &gt; 99 999 chars) text clips. It will speed up search..
        /// </summary>
        internal static string SearchIgnoreBigTextsDescription {
            get {
                return ResourceManager.GetString("SearchIgnoreBigTextsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search &quot;%&quot; as any char sequence.
        /// </summary>
        internal static string SearchWildcards {
            get {
                return ResourceManager.GetString("SearchWildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search char &quot;%&quot; from filter as any char sequence. For example filter &quot;po%o&quot; will match &quot;potato&quot;. .
        /// </summary>
        internal static string SearchWildcardsDescription {
            get {
                return ResourceManager.GetString("SearchWildcardsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search independent words.
        /// </summary>
        internal static string SearchWordsIndependently {
            get {
                return ResourceManager.GetString("SearchWordsIndependently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search every word from filter independently. For example &quot;pot web&quot; will match &quot;Our website sells potato&quot;. .
        /// </summary>
        internal static string SearchWordsIndependentlyDescription {
            get {
                return ResourceManager.GetString("SearchWordsIndependentlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show clip source icon column.
        /// </summary>
        internal static string ShowApplicationIconColumn {
            get {
                return ResourceManager.GetString("ShowApplicationIconColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show column with icon from application where clip was copied.
        /// </summary>
        internal static string ShowApplicationIconColumnDescription {
            get {
                return ResourceManager.GetString("ShowApplicationIconColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show native text formatting.
        /// </summary>
        internal static string ShowNativeTextFormatting {
            get {
                return ResourceManager.GetString("ShowNativeTextFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show native text formatting for RTF and HTML clips (CTRL+N). However, text greater than 10K chars after loading will be shown without formatting until user click in text field..
        /// </summary>
        internal static string ShowNativeTextFormattingDescription {
            get {
                return ResourceManager.GetString("ShowNativeTextFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show secondary columns.
        /// </summary>
        internal static string ShowSecondaryColumns {
            get {
                return ResourceManager.GetString("ShowSecondaryColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show secondary columns in list.
        /// </summary>
        internal static string ShowSecondaryColumnsDescription {
            get {
                return ResourceManager.GetString("ShowSecondaryColumnsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show visual clip weight column.
        /// </summary>
        internal static string ShowSizeColumn {
            get {
                return ResourceManager.GetString("ShowSizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column will show visual weight (number of digits in visual size) of clip.
        /// </summary>
        internal static string ShowSizeColumnDescription {
            get {
                return ResourceManager.GetString("ShowSizeColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text compare application.
        /// </summary>
        internal static string TextCompareApplication {
            get {
                return ResourceManager.GetString("TextCompareApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave empty to use automatic search application, which looks for Beyond Compare, ExamDiff Pro, 
        ///WinMerge, Araxis Merge, DiffMerge, Kdiff3. Text compare command is %application% %file1% %file2%.
        /// </summary>
        internal static string TextCompareApplicationDescription {
            get {
                return ResourceManager.GetString("TextCompareApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text (TXT) file editor application.
        /// </summary>
        internal static string TextEditor {
            get {
                return ResourceManager.GetString("TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in &quot;Open file&quot; command for clip. Leave empty to use default OS application for edit text (TXT) files..
        /// </summary>
        internal static string TextEditorDescription {
            get {
                return ResourceManager.GetString("TextEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use formatting in duplicate detection.
        /// </summary>
        internal static string UseFormattingInDuplicateDetection {
            get {
                return ResourceManager.GetString("UseFormattingInDuplicateDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use native text formatting in duplicate detection. Else only plain text will be used for detecting duplicate of text clip.
        /// </summary>
        internal static string UseFormattingInDuplicateDetectionDescription {
            get {
                return ResourceManager.GetString("UseFormattingInDuplicateDetectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application user settings path.
        /// </summary>
        internal static string UserSettingsPath {
            get {
                return ResourceManager.GetString("UserSettingsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with user settings and default database file are here.
        /// </summary>
        internal static string UserSettingsPathDescription {
            get {
                return ResourceManager.GetString("UserSettingsPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window auto position on open.
        /// </summary>
        internal static string WindowAutoPosition {
            get {
                return ResourceManager.GetString("WindowAutoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, then, if possible, window will open near place of text input or in center of active window. If disabled, window will open in position where it was last closed..
        /// </summary>
        internal static string WindowAutoPositionDescription {
            get {
                return ResourceManager.GetString("WindowAutoPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word wrap.
        /// </summary>
        internal static string WordWrap {
            get {
                return ResourceManager.GetString("WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word wrap in clip text field (CTRL+W).
        /// </summary>
        internal static string WordWrapDescription {
            get {
                return ResourceManager.GetString("WordWrapDescription", resourceCulture);
            }
        }
    }
}
