//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipAngel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipAngel.Properties.Resource_RU", typeof(Resource_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to все метки.
        /// </summary>
        internal static string allMarks {
            get {
                return ResourceManager.GetString("allMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to все типы.
        /// </summary>
        internal static string allTypes {
            get {
                return ResourceManager.GetString("allTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Б.
        /// </summary>
        internal static string ByteUnit {
            get {
                return ResourceManager.GetString("ByteUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно вставить из непривилегированного процесса в привилегированное окно. Попробуйте запустить программу от имени администратора..
        /// </summary>
        internal static string CantPasteInElevatedWindow {
            get {
                return ResourceManager.GetString("CantPasteInElevatedWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С.
        /// </summary>
        internal static string CharUnit {
            get {
                return ResourceManager.GetString("CharUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать остальной текст.
        /// </summary>
        internal static string CutMarker {
            get {
                return ResourceManager.GetString("CutMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение заголовка клипа.
        /// </summary>
        internal static string EditClipTitle {
            get {
                return ResourceManager.GetString("EditClipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КОНЕЦ.
        /// </summary>
        internal static string EndMarker {
            get {
                return ResourceManager.GetString("EndMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to любимые.
        /// </summary>
        internal static string favorite {
            get {
                return ResourceManager.GetString("favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to файл.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/p/clip-angel/wiki/DescriptionRU/.
        /// </summary>
        internal static string HelpPage {
            get {
                return ResourceManager.GetString("HelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистите строку для использования автозаголовка.
        /// </summary>
        internal static string HowUseAutoTitle {
            get {
                return ResourceManager.GetString("HowUseAutoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to карт.
        /// </summary>
        internal static string img {
            get {
                return ResourceManager.GetString("img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для полной смены языка возможно потребуется перезапуск программы.
        /// </summary>
        internal static string LangRestart {
            get {
                return ResourceManager.GetString("LangRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая версия доступна. Для обновления нажмите кнопку в верхней командной панели..
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий клип.
        /// </summary>
        internal static string NextClip {
            get {
                return ResourceManager.GetString("NextClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат пикселя.
        /// </summary>
        internal static string PixelFormat {
            get {
                return ResourceManager.GetString("PixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to текст.
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить на.
        /// </summary>
        internal static string UpdateTo {
            get {
                return ResourceManager.GetString("UpdateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to полезные.
        /// </summary>
        internal static string used {
            get {
                return ResourceManager.GetString("used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визуальный вес клипа (количество цифр в числе, отражающем визуальный размер клипа).
        /// </summary>
        internal static string VisualWeightTooltip {
            get {
                return ResourceManager.GetString("VisualWeightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы используете последнюю версию.
        /// </summary>
        internal static string YouLatestVersion {
            get {
                return ResourceManager.GetString("YouLatestVersion", resourceCulture);
            }
        }
    }
}
